### ISSUE TITLE
Conditional shell operations

### ISSUE THREAD

**Issue by adam12** [skx/marionette#34]
Enjoying the project so far, but ran into something and I'm curious if you have any thoughts on how you might tackle conditional shell operations? ie. calling `useradd` only if the user doesn't exist.

I ended up something like this, but:

1. I had to force shell redirection to get the command to be evaluated through the shell (using `||` wasn't enough).
2. It always considers itself "changed".

```
shell {
    name => "Create ${user} user",
    command => "id ${user} >/dev/null || useradd --system --no-create-home ${user}"
}
```

What I think might work would be something along the lines of:

```
shell {
    name => "Create ${user} user",
    command => "useradd --system --no-create-home ${user}",
    unless => true("id ${user}")
}
```

I think adding `true` and `false` might be easy enough to support as conditionals, but I'm yet to try it.

**Comment by skx** [comment]
> I had to force shell redirection to get the command to be evaluated through the shell (using || wasn't enough).

That seems like a different bug, and something that should be fixed.  (Just adding "|" to the list of characters that triggers a real shell.

But to address the meat of your question I think the way I'd handle this is to run:

```
let existing = `id 2>/dev/null`
```

Then:

```
  if => true(`existing`);
  unless => empty(`existing`);
```

The real issue is that your approach wants to run `true` with the exit-code of the shell-command and that's something that is unfortunately thrown away.   Capturing the output, and ignoring any error, into a variable seems like it should work though.  That would result in a variable containing:

* Details of existing user.
* Empty string, for missing user.  (STDERR would contain "no such user", so we throw that away.)

With that we can then use your proposed "true"  (i.e. non-empty string) and "false" (to mean empty) successfully.

Does that seem sane to you?  The need to store in a variable is unfortunate, but otherwise I think there would need to be a primitives for `command_succeeds` or `command_fails` with the string argument, and that starts to look ugly in its own way..

**Comment by skx** [comment]
I've submitted a pull-request with a simple implementation/fix, if that looks good to you?

I guess you can test it with your proposed module:

```
 unless => true(`id ${user} 2>/dev/null`)
```

(With or without the use of the variable!)

**Comment by adam12** [comment]
> That seems like a different bug, and something that should be fixed. (Just adding "|" to the list of characters that triggers a real shell.

I agree. I almost wonder if `&&` and `||` would be good to add as well, tho that said the other changes might negate them being necessary.

> I've submitted a pull-request with a simple implementation/fix, if that looks good to you?

The fix looks good. I'm not sure on the naming (if I'm being picky :P). Seems like `present` and `blank` might be more appropriate?

I had imagined that the status codes of the subprocess to be more useful, similar to how `exists` works currently, but I can recognize how only checking zero and non-zero might not be that useful.

Relying on stdout just seemed potentially more brittle, but that was just an assumption.

**Comment by skx** [comment]
>I agree. I almost wonder if && and || would be good to add as well, tho that said the other changes might negate them being necessary.

I've added `&` as another "force-shell" character.

> The fix looks good. I'm not sure on the naming (if I'm being picky :P). Seems like present and blank might be more appropriate?

I've added aliases:

```
        Register("true", True)
        Register("nonempty", True)
        Register("set", True)

        Register("false", False)
        Register("empty", False)
        Register("unset", False)
```

> I had imagined that the status codes of the subprocess to be more useful, similar to how exists works currently, but I can recognize how only checking zero and non-zero might not be that useful.

Yes I guess that's a good call.  I'm not sure what to do there - I could imagine setting a variable "last-exit" or similar, but then it gets magic/messy if the naming isn't obvious.

I could imagine using `$?` but that feels like it's very unlike anything else we've used so it feels like a bad choice.  I guess that needs some more thought.

For the moment I'll merge the PR and see how that helps.

**Comment by skx** [comment]
So the MR referenced added `true` and `false`, as well as synonyms.

Upon reflection I'm going to close this with a second MR which will add:

* success( "command");
* failure( "command");

They will work on the exit-code of the command-specified.

**Comment by adam12** [comment]
> They will work on the exit-code of the command-specified.

Worked perfectly! Much thanks.
