### ISSUE TITLE
Conditional includes

### ISSUE THREAD

**Issue by alexwhitman** [skx/marionette#57]
`if` and `unless` are useful in rules but get repetitive if multiple rules require the same condition:

```
package {
    ....
    if => equal("${ARCH}", "x86_64")
}
file {
    ....
    if => equal("${ARCH}", "x86_64")
}
file {
    ....
    if => equal("${ARCH}", "x86_64")
}
```

A nicer implementation might be to include files based on conditionals:
```
include "x86_64_stuff.txt" if equal("${ARCH}", "x86_64")
```
This could use the same conditionals that are available for rules.

Another alternative would be to allow wrapping `if` and `unless` around rules:
```
if equal("${ARCH}", "x86_64") {
    package {
        ....
    }

    # ${ARCH} equals "x86_64" and ${VAR} equals "foo"
    if equal("${VAR}", "foo") {
        file {
            ....
        }
    }
}
```

**Comment by skx** [comment]
That's good feedback, thank-you!

In terms of the parser-changes the first suggestion - add an if/unless clause to the include statement - would be easiest to implement.

I'd be happy to add that once I've finished up the user module in #56.

**Comment by skx** [comment]
So I'd opened #58 for this, but it turns out that there were too many issues so that was closed.

The new approach is to convert our implementation to something more akin to a tree-walking interpreter:

* The parser will not expand backticks, or file-inclusion.
* Instead the parser will return an AST comprised of three distinct node-types:
  * File inclusion.
  * Variable assignments.
  * Actual rules.

This means that the evaluator will not solely be passed an array of "Rule"  objects, instead it will receive the AST and walk that, switching on node-types:

* Assignments will result in environment-updates.
* Inclusions will result in recursion
* Rules will be processed as they should be.

This will be a significant change in terms of the implementation, however the steps are simple and well-known and the functionality should be unchanged...
